{
    "openapi": "3.0.0",
    "info": {
        "version": "1.0.0",
        "title": "dev-pipes-token",
        "termsOfService": "https://ui.us-east.tinybird.co/terms",
        "contact": {
            "email": "support@tinybird.co"
        }
    },
    "servers": [
        {
            "url": "https://api.us-east.tinybird.co/v0"
        }
    ],
    "security": [
        {
            "TokenBearerHeader": [
                "BEARER_TOKEN"
            ]
        },
        {
            "TokenQueryString": [
                "BEARER_TOKEN"
            ]
        }
    ],
    "paths": {
        "/pipes/count_keyword_matches.{format}": {
            "get": {
                "tags": [
                    "Pipes"
                ],
                "summary": "count_keyword_matches",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:count_keyword_matches",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:count_keyword_matches",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "count_keyword_matches_get"
            },
            "post": {
                "tags": [
                    "Pipes"
                ],
                "summary": "count_keyword_matches",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:count_keyword_matches",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:count_keyword_matches",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "count_keyword_matches_post"
            }
        },
        "/pipes/average_sentiment_comments.{format}": {
            "get": {
                "tags": [
                    "Pipes"
                ],
                "summary": "average_sentiment_comments",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:average_sentiment_comments",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:average_sentiment_comments",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "average_sentiment_comments_get"
            },
            "post": {
                "tags": [
                    "Pipes"
                ],
                "summary": "average_sentiment_comments",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:average_sentiment_comments",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:average_sentiment_comments",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "average_sentiment_comments_post"
            }
        },
        "/pipes/total_likes.{format}": {
            "get": {
                "tags": [
                    "Pipes"
                ],
                "summary": "total_likes",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:total_likes",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:total_likes",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "total_likes_get"
            },
            "post": {
                "tags": [
                    "Pipes"
                ],
                "summary": "total_likes",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:total_likes",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:total_likes",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "total_likes_post"
            }
        },
        "/pipes/video_matches.{format}": {
            "get": {
                "tags": [
                    "Pipes"
                ],
                "summary": "video_matches",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:video_matches",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:video_matches",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "video_matches_get"
            },
            "post": {
                "tags": [
                    "Pipes"
                ],
                "summary": "video_matches",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:video_matches",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:video_matches",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "video_matches_post"
            }
        },
        "/pipes/day_of_week_counts.{format}": {
            "get": {
                "tags": [
                    "Pipes"
                ],
                "summary": "day_of_week_counts",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:day_of_week_counts",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:day_of_week_counts",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "day_of_week_counts_get"
            },
            "post": {
                "tags": [
                    "Pipes"
                ],
                "summary": "day_of_week_counts",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:day_of_week_counts",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:day_of_week_counts",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "day_of_week_counts_post"
            }
        },
        "/pipes/filter_keyword_and_date_index_improved_2.{format}": {
            "get": {
                "tags": [
                    "Pipes"
                ],
                "summary": "filter_keyword_and_date_index_improved_2",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:filter_keyword_and_date_index_improved_2",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:filter_keyword_and_date_index_improved_2",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "filter_keyword_and_date_index_improved_2_get"
            },
            "post": {
                "tags": [
                    "Pipes"
                ],
                "summary": "filter_keyword_and_date_index_improved_2",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:filter_keyword_and_date_index_improved_2",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:filter_keyword_and_date_index_improved_2",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "filter_keyword_and_date_index_improved_2_post"
            }
        },
        "/pipes/count_video_matches.{format}": {
            "get": {
                "tags": [
                    "Pipes"
                ],
                "summary": "count_video_matches",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:count_video_matches",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:count_video_matches",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "count_video_matches_get"
            },
            "post": {
                "tags": [
                    "Pipes"
                ],
                "summary": "count_video_matches",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:count_video_matches",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:count_video_matches",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "count_video_matches_post"
            }
        },
        "/pipes/total_replies.{format}": {
            "get": {
                "tags": [
                    "Pipes"
                ],
                "summary": "total_replies",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:total_replies",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:total_replies",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "total_replies_get"
            },
            "post": {
                "tags": [
                    "Pipes"
                ],
                "summary": "total_replies",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:total_replies",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:total_replies",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "total_replies_post"
            }
        },
        "/pipes/average_per_day_of_week.{format}": {
            "get": {
                "tags": [
                    "Pipes"
                ],
                "summary": "average_per_day_of_week",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:average_per_day_of_week",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:average_per_day_of_week",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "average_per_day_of_week_get"
            },
            "post": {
                "tags": [
                    "Pipes"
                ],
                "summary": "average_per_day_of_week",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:average_per_day_of_week",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:average_per_day_of_week",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "average_per_day_of_week_post"
            }
        },
        "/pipes/sentiment_by_keyword.{format}": {
            "get": {
                "tags": [
                    "Pipes"
                ],
                "summary": "sentiment_by_keyword",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:sentiment_by_keyword",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:sentiment_by_keyword",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "sentiment_by_keyword_get"
            },
            "post": {
                "tags": [
                    "Pipes"
                ],
                "summary": "sentiment_by_keyword",
                "description": "",
                "security": [
                    {
                        "TokenBearerHeader": [
                            "PIPES:READ:sentiment_by_keyword",
                            "ADMIN"
                        ]
                    },
                    {
                        "TokenQueryString": [
                            "PIPES:READ:sentiment_by_keyword",
                            "ADMIN"
                        ]
                    }
                ],
                "operationId": "sentiment_by_keyword_post"
            }
        }
    },
    "components": {
        "securitySchemes": {
            "TokenBearerHeader": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            },
            "TokenQueryString": {
                "type": "apiKey",
                "in": "query",
                "name": "token"
            }
        }
    }
}